# A single small PostgreSQL instance in the private subnets. It stores the
# relational side of the app (users' document rows in P7 and, with the pgvector
# extension, the embedding chunks) — DynamoDB keeps the document metadata.
#
# One concern per file: main.tf (password, subnet group, instance) · ssm.tf (the
# two Parameter Store entries the API reads at boot).

# The password is generated by Terraform and never typed by a human, so it never
# reaches git. It does land in the state file — which is why the state bucket is
# private, versioned and encrypted. Phase 4 moves this to Secrets Manager, whose
# point is rotation, not secrecy.
#
# override_special limits the symbol set to `-` and `_`: both are safe unescaped
# inside the `DATABASE_URL` the API builds, unlike `@`, `/`, `:` or `#`.
resource "random_password" "master" {
  length           = 32
  special          = true
  override_special = "-_"
}

# A DB subnet group is how RDS is told which subnets it may place the instance
# in. AWS requires subnets in at least two AZs even for a single-AZ instance,
# because a failover or a maintenance replacement has to have somewhere to go.
resource "aws_db_subnet_group" "this" {
  name       = var.identifier
  subnet_ids = var.subnet_ids

  tags = {
    Name = var.identifier
  }
}

resource "aws_db_instance" "this" {
  identifier     = var.identifier
  engine         = "postgres"
  instance_class = var.instance_class

  # Major version only: AWS then picks the latest 16.x minor at create time. Pin
  # a full `16.x` if a plan ever shows an upgrade that is not wanted.
  engine_version = "16"

  # 20 GB is the minimum for gp3. gp3 gives a fixed 3000 IOPS baseline at the
  # same price as gp2, whose IOPS scale with size (60 for 20 GB) — strictly
  # better here.
  allocated_storage = 20
  storage_type      = "gp3"

  # Encryption at rest with the AWS-managed `aws/rds` key, which is free. It can
  # ONLY be set when the instance is created: turning it on later forces a
  # replace (snapshot + restore), so it is on from the start even in dev.
  storage_encrypted = true

  # Multi-AZ keeps a synchronous standby in another AZ for automatic failover —
  # it doubles the bill and serves no reads. A dev database that can be rebuilt
  # does not need it. (A read replica is the other shape: asynchronous, for
  # reads, not for failover.)
  multi_az = false

  # No public IP and no route from the internet: the only way in is from inside
  # the VPC, through the security group. This is the pairing that makes the
  # private subnets worth having.
  publicly_accessible    = false
  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.security_group_id]

  db_name  = var.db_name
  username = var.username
  password = random_password.master.result

  # One day of automated backups is the minimum that still leaves point-in-time
  # recovery switched on; 0 would disable backups entirely.
  backup_retention_period = 1

  # Both deliberately set for a dev database that is meant to be disposable:
  # deletion protection would block `terraform destroy`, and a final snapshot
  # would silently keep billing storage after the instance is gone.
  deletion_protection = false
  skip_final_snapshot = true

  # Apply changes now instead of waiting for the weekly maintenance window. Fine
  # in dev; in production this is how an unplanned restart happens mid-day.
  apply_immediately = true

  # Minor versions carry the security fixes and are backwards compatible, so
  # they are taken automatically. Major versions are never automatic.
  auto_minor_version_upgrade = true

  tags = {
    Name = var.identifier
  }
}
