# The API never receives the password as a variable or an environment value in
# git: it reads these two parameters at boot with the instance role (P8). Splitting
# them means a reader can be granted the host without the password.

# SecureString is encrypted with the AWS-managed `aws/ssm` KMS key, which is
# free and needs no key policy of its own — a reader only needs
# `ssm:GetParameter` on this ARN, no separate `kms:Decrypt`. A customer-managed
# key would add 1 USD/month and a policy to maintain, for no gain here.
resource "aws_ssm_parameter" "master_password" {
  name  = "${var.ssm_prefix}/master_password"
  type  = "SecureString"
  value = random_password.master.result

  description = "RDS master password for ${var.identifier}, generated by Terraform."

  tags = {
    Name = "${var.ssm_prefix}/master_password"
  }
}

# The host is not a secret, so it is a plain String — cheaper to read and
# visible in the console, which helps when debugging a connection. It is stored
# rather than passed as a variable so the API's user data has a single place to
# look, and a rebuilt instance publishes its new endpoint automatically.
resource "aws_ssm_parameter" "host" {
  name  = "${var.ssm_prefix}/host"
  type  = "String"
  value = aws_db_instance.this.address

  description = "Endpoint hostname of ${var.identifier} (no port, no scheme)."

  tags = {
    Name = "${var.ssm_prefix}/host"
  }
}
