/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_documents_get"];
        put?: never;
        /** Create Document */
        post: operations["create_document_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiResponse[Document] */
        ApiResponse_Document_: {
            data: components["schemas"]["Document"];
        };
        /** ApiResponse[HealthOut] */
        ApiResponse_HealthOut_: {
            data: components["schemas"]["HealthOut"];
        };
        /** ApiResponse[MeOut] */
        ApiResponse_MeOut_: {
            data: components["schemas"]["MeOut"];
        };
        /**
         * CreateDocumentRequest
         * @description Phase 1 stub body. Phase 2 replaces this route with an upload-url flow.
         */
        CreateDocumentRequest: {
            /** File Name */
            file_name: string;
        };
        /**
         * Document
         * @description A document owned by one user. Frozen: build a new one instead of mutating.
         */
        Document: {
            /** Document Id */
            document_id: string;
            /** User Id */
            user_id: string;
            /** File Name */
            file_name: string;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: number | null;
        };
        /**
         * DocumentStatus
         * @description Lifecycle of an uploaded document, from upload to searchable.
         * @enum {string}
         */
        DocumentStatus: "PENDING" | "EXTRACTED" | "READY" | "FAILED";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /** Version */
            version: string;
        };
        /** MeOut */
        MeOut: {
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
        };
        /**
         * PageMeta
         * @description Pagination info. `next_cursor` is opaque: pass it back untouched.
         */
        PageMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Has Next */
            has_next: boolean;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PaginatedResponse[Document] */
        PaginatedResponse_Document_: {
            /** Data */
            data: components["schemas"]["Document"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_HealthOut_"];
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MeOut_"];
                };
            };
        };
    };
    list_documents_documents_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Document_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Document_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
